development: &defaults
  adapter      : postgresql
  encoding     : unicode
  database     : asc_development
  pool         : 5
  host         : 127.0.0.1
  username     : john
  min_messages : WARNING

test:
  <<: *defaults
  database     : asc_test